_wandb:
    value:
        cli_version: 0.18.7
        m: []
        python_version: 3.8.10
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 13
                - 15
                - 16
                - 22
                - 23
                - 35
                - 55
            "4": 3.8.10
            "5": 0.18.7
            "8":
                - 5
            "12": 0.18.7
            "13": linux-x86_64
batch_size:
    value: 256
buffer_size:
    value: 1000000
ent_coef:
    value: auto
gamma:
    value: 0.98
goal_selection_strategy:
    value: future
learning_rate:
    value: 0.00025
learning_starts:
    value: 1000
maximum_episode_length:
    value: 600
n_sampled_goal:
    value: 4
seed_num:
    value: 0
skip_frame:
    value: 3
target_entropy:
    value: -9
task_name:
    value: picking
tau:
    value: 0.01
tensorboard_log:
    value: baseline_picking_her_sac
total_time_steps:
    value: 60000000
