_wandb:
    value:
        cli_version: 0.18.7
        m: []
        python_version: 3.7.16
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 13
                - 15
                - 16
                - 23
                - 55
            "4": 3.7.16
            "5": 0.18.7
            "8":
                - 5
            "12": 0.18.7
            "13": linux-x86_64
eval:
    value: true
log_dir:
    value: highest_reward_sequencing_logs
pretrained_path:
    value: null
seed:
    value: 0
skip_frame:
    value: 3
task:
    value: pushing
test_episodes:
    value: 10
timesteps:
    value: 50000
train:
    value: true
use_wandb:
    value: true
