_wandb:
    value:
        cli_version: 0.18.7
        m: []
        python_version: 3.7.16
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 13
                - 15
                - 16
                - 22
                - 23
                - 35
                - 55
            "4": 3.7.16
            "5": 0.18.7
            "8":
                - 5
            "12": 0.18.7
            "13": linux-x86_64
batch_size:
    value: 256
buffer_size:
    value: 1000000
ent_coef:
    value: auto
gamma:
    value: 0.99
goal_selection_strategy:
    value: future
gradient_steps:
    value: 1
graph_curriculum_enabled:
    value: true
learning_rate:
    value: 0.0003
learning_starts:
    value: 5000
maximum_episode_length:
    value: 400
n_sampled_goal:
    value: 4
policy_kwargs:
    value:
        activation_fn: torch.nn.modules.activation.ReLU
        net_arch:
            - 512
            - 512
seed_num:
    value: 0
skip_frame:
    value: 3
target_entropy:
    value: -12
task_name:
    value: picking
tau:
    value: 0.005
tensorboard_log:
    value: baseline_picking_her_sac_curriculum
total_time_steps:
    value: 2000000
train_freq:
    value: 1
