_wandb:
    value:
        cli_version: 0.18.7
        m: []
        python_version: 3.7.16
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 2
                - 13
                - 15
                - 16
                - 23
                - 35
                - 55
            "4": 3.7.16
            "5": 0.18.7
            "8":
                - 5
            "12": 0.18.7
            "13": linux-x86_64
log_dir:
    value: meta_teacher_student_logs
meta_episodes:
    value: 30
seed:
    value: 0
student_pretrained_path:
    value: ppo_pushing_sb3/final_model.zip
student_train_steps:
    value: 50000
task:
    value: pushing
teacher_batch_size:
    value: 32
teacher_buffer_size:
    value: 10000
teacher_gamma:
    value: 0.99
teacher_lr:
    value: 0.001
teacher_target_update:
    value: 10
use_wandb:
    value: true
