_wandb:
    value:
        cli_version: 0.18.7
        m: []
        python_version: 3.7.16
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 2
                - 13
                - 15
                - 16
                - 23
                - 34
                - 35
                - 55
                - 61
            "4": 3.7.16
            "5": 0.18.7
            "8":
                - 5
            "12": 0.18.7
            "13": linux-x86_64
cm_threshold:
    value: 0.05
curriculum_type:
    value: CausalMatching_Curriculum_on_PPO
seed:
    value: 0
task_name:
    value: pushing
timesteps_per_intervention:
    value: 300000
