_current_progress_remaining:
    value: -0.009254400000000107
_custom_logger:
    value: "False"
_episode_num:
    value: 0
_last_episode_starts:
    value: |-
        [ True  True  True  True  True  True  True  True  True  True  True  True
          True  True  True  True]
_last_obs:
    value: |-
        [[ 1.          0.22178988  0.43350048 -0.26179939  0.22178988  0.43350048
          -0.26179939  0.22178988  0.43350048 -0.26179939  0.          0.
           0.          0.          0.          0.          0.          0.
           0.         -0.1189      0.31727417 -0.77654834  0.33421749 -0.05566666
          -0.77654834 -0.21531749 -0.26160751 -0.77654834  1.          0.
           0.          0.          0.         -0.16       -0.87        0.
           0.          0.          0.1         0.          0.          0.
           0.          0.          0.         20.          0.          0.
           0.          0.          0.16       -0.87        0.          0.
           0.          0.1       ]
         [ 1.          0.22178988  0.43350048 -0.26179939  0.22178988  0.43350048
          -0.26179939  0.22178988  0.43350048 -0.26179939  0.          0.
           0.          0.          0.          0.          0.          0.
           0.         -0.1189      0.31727417 -0.77654834  0.33421749 -0.05566666
          -0.77654834 -0.21531749 -0.26160751 -0.77654834  1.          0.
           0.          0.          0.         -0.16       -0.87        0.
           0.          0.          0.1         0.          0.          0.
           0.          0.          0.         20.          0.          0.
           0.          0.          0.16       -0.87        0.          0.
           0.          0.1       ]
         [ 1.          0.22178988  0.43350048 -0.26179939  0.22178988  0.43350048
          -0.26179939  0.22178988  0.43350048 -0.26179939  0.          0.
           0.          0.          0.          0.          0.          0.
           0.         -0.1189      0.31727417 -0.77654834  0.33421749 -0.05566666
          -0.77654834 -0.21531749 -0.26160751 -0.77654834  1.          0.
           0.          0.          0.         -0.16       -0.87        0.
           0.          0.          0.1         0.          0.          0.
           0.          0.          0.         20.          0.          0.
           0.          0.          0.16       -0.87        0.          0.
           0.          0.1       ]
         [ 1.          0.22178988  0.43350048 -0.26179939  0.22178988  0.43350048
          -0.26179939  0.22178988  0.43350048 -0.26179939  0.          0.
           0.          0.          0.          0.          0.          0.
           0.         -0.1189      0.31727417 -0.77654834  0.33421749 -0.05566666
          -0.77654834 -0.21531749 -0.26160751 -0.77654834  1.          0.
           0.          0.          0.         -0.16       -0.87        0.
           0.          0.          0.1         0.          0.          0.
           0.          0.          0.         20.          0.          0.
           0.          0.          0.16       -0.87        0.          0.
           0.          0.1       ]
         [ 1.          0.22178988  0.43350048 -0.26179939  0.22178988  0.43350048
          -0.26179939  0.22178988  0.43350048 -0.26179939  0.          0.
           0.          0.          0.          0.          0.          0.
           0.         -0.1189      0.31727417 -0.77654834  0.33421749 -0.05566666
          -0.77654834 -0.21531749 -0.26160751 -0.77654834  1.          0.
           0.          0.          0.         -0.16       -0.87        0.
           0.          0.          0.1         0.          0.          0.
           0.          0.          0.         20.          0.          0.
           0.          0.          0.16       -0.87        0.          0.
           0.          0.1       ]
         [ 1.          0.22178988  0.43350048 -0.26179939  0.22178988  0.43350048
          -0.26179939  0.22178988  0.43350048 -0.26179939  0.          0.
           0.          0.          0.          0.          0.          0.
           0.         -0.1189      0.31727417 -0.77654834  0.33421749 -0.05566666
          -0.77654834 -0.21531749 -0.26160751 -0.77654834  1.          0.
           0.          0.          0.         -0.16       -0.87        0.
           0.          0.          0.1         0.          0.          0.
           0.          0.          0.         20.          0.          0.
           0.          0.          0.16       -0.87        0.          0.
           0.          0.1       ]
         [ 1.          0.22178988  0.43350048 -0.26179939  0.22178988  0.43350048
          -0.26179939  0.22178988  0.43350048 -0.26179939  0.          0.
           0.          0.          0.          0.          0.          0.
           0.         -0.1189      0.31727417 -0.77654834  0.33421749 -0.05566666
          -0.77654834 -0.21531749 -0.26160751 -0.77654834  1.          0.
           0.          0.          0.         -0.16       -0.87        0.
           0.          0.          0.1         0.          0.          0.
           0.          0.          0.         20.          0.          0.
           0.          0.          0.16       -0.87        0.          0.
           0.          0.1       ]
         [ 1.          0.22178988  0.43350048 -0.26179939  0.22178988  0.43350048
          -0.26179939  0.22178988  0.43350048 -0.26179939  0.          0.
           0.          0.          0.          0.          0.          0.
           0.         -0.1189      0.31727417 -0.77654834  0.33421749 -0.05566666
          -0.77654834 -0.21531749 -0.26160751 -0.77654834  1.          0.
           0.          0.          0.         -0.16       -0.87        0.
           0.          0.          0.1         0.          0.          0.
           0.          0.          0.         20.          0.          0.
           0.          0.          0.16       -0.87        0.          0.
           0.          0.1       ]
         [ 1.          0.22178988  0.43350048 -0.26179939  0.22178988  0.43350048
          -0.26179939  0.22178988  0.43350048 -0.26179939  0.          0.
           0.          0.          0.          0.          0.          0.
           0.         -0.1189      0.31727417 -0.77654834  0.33421749 -0.05566666
          -0.77654834 -0.21531749 -0.26160751 -0.77654834  1.          0.
           0.          0.          0.         -0.16       -0.87        0.
           0.          0.          0.1         0.          0.          0.
           0.          0.          0.         20.          0.          0.
           0.          0.          0.16       -0.87        0.          0.
           0.          0.1       ]
         [ 1.          0.22178988  0.43350048 -0.26179939  0.22178988  0.43350048
          -0.26179939  0.22178988  0.43350048 -0.26179939  0.          0.
           0.          0.          0.          0.          0.          0.
           0.         -0.1189      0.31727417 -0.77654834  0.33421749 -0.05566666
          -0.77654834 -0.21531749 -0.26160751 -0.77654834  1.          0.
           0.          0.          0.         -0.16       -0.87        0.
           0.          0.          0.1         0.          0.          0.
           0.          0.          0.         20.          0.          0.
           0.          0.          0.16       -0.87        0.          0.
           0.          0.1       ]
         [ 1.          0.22178988  0.43350048 -0.26179939  0.22178988  0.43350048
          -0.26179939  0.22178988  0.43350048 -0.26179939  0.          0.
           0.          0.          0.          0.          0.          0.
           0.         -0.1189      0.31727417 -0.77654834  0.33421749 -0.05566666
          -0.77654834 -0.21531749 -0.26160751 -0.77654834  1.          0.
           0.          0.          0.         -0.16       -0.87        0.
           0.          0.          0.1         0.          0.          0.
           0.          0.          0.         20.          0.          0.
           0.          0.          0.16       -0.87        0.          0.
           0.          0.1       ]
         [ 1.          0.22178988  0.43350048 -0.26179939  0.22178988  0.43350048
          -0.26179939  0.22178988  0.43350048 -0.26179939  0.          0.
           0.          0.          0.          0.          0.          0.
           0.         -0.1189      0.31727417 -0.77654834  0.33421749 -0.05566666
          -0.77654834 -0.21531749 -0.26160751 -0.77654834  1.          0.
           0.          0.          0.         -0.16       -0.87        0.
           0.          0.          0.1         0.          0.          0.
           0.          0.          0.         20.          0.          0.
           0.          0.          0.16       -0.87        0.          0.
           0.          0.1       ]
         [ 1.          0.22178988  0.43350048 -0.26179939  0.22178988  0.43350048
          -0.26179939  0.22178988  0.43350048 -0.26179939  0.          0.
           0.          0.          0.          0.          0.          0.
           0.         -0.1189      0.31727417 -0.77654834  0.33421749 -0.05566666
          -0.77654834 -0.21531749 -0.26160751 -0.77654834  1.          0.
           0.          0.          0.         -0.16       -0.87        0.
           0.          0.          0.1         0.          0.          0.
           0.          0.          0.         20.          0.          0.
           0.          0.          0.16       -0.87        0.          0.
           0.          0.1       ]
         [ 1.          0.22178988  0.43350048 -0.26179939  0.22178988  0.43350048
          -0.26179939  0.22178988  0.43350048 -0.26179939  0.          0.
           0.          0.          0.          0.          0.          0.
           0.         -0.1189      0.31727417 -0.77654834  0.33421749 -0.05566666
          -0.77654834 -0.21531749 -0.26160751 -0.77654834  1.          0.
           0.          0.          0.         -0.16       -0.87        0.
           0.          0.          0.1         0.          0.          0.
           0.          0.          0.         20.          0.          0.
           0.          0.          0.16       -0.87        0.          0.
           0.          0.1       ]
         [ 1.          0.22178988  0.43350048 -0.26179939  0.22178988  0.43350048
          -0.26179939  0.22178988  0.43350048 -0.26179939  0.          0.
           0.          0.          0.          0.          0.          0.
           0.         -0.1189      0.31727417 -0.77654834  0.33421749 -0.05566666
          -0.77654834 -0.21531749 -0.26160751 -0.77654834  1.          0.
           0.          0.          0.         -0.16       -0.87        0.
           0.          0.          0.1         0.          0.          0.
           0.          0.          0.         20.          0.          0.
           0.          0.          0.16       -0.87        0.          0.
           0.          0.1       ]
         [ 1.          0.22178988  0.43350048 -0.26179939  0.22178988  0.43350048
          -0.26179939  0.22178988  0.43350048 -0.26179939  0.          0.
           0.          0.          0.          0.          0.          0.
           0.         -0.1189      0.31727417 -0.77654834  0.33421749 -0.05566666
          -0.77654834 -0.21531749 -0.26160751 -0.77654834  1.          0.
           0.          0.          0.         -0.16       -0.87        0.
           0.          0.          0.1         0.          0.          0.
           0.          0.          0.         20.          0.          0.
           0.          0.          0.16       -0.87        0.          0.
           0.          0.1       ]]
_last_original_obs:
    value: None
_logger:
    value: <stable_baselines3.common.logger.Logger object at 0x7f9cd4ed6c10>
_n_updates:
    value: 1155
_num_timesteps_at_start:
    value: 0
_total_timesteps:
    value: 3000000
_vec_normalize_env:
    value: None
_wandb:
    value:
        cli_version: 0.18.7
        m: []
        python_version: 3.7.16
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 1
                - 13
                - 15
                - 16
                - 22
                - 23
                - 35
                - 55
            "4": 3.7.16
            "5": 0.18.7
            "8":
                - 5
            "12": 0.18.7
            "13": linux-x86_64
action_noise:
    value: None
action_space:
    value: Box(9,)
algo:
    value: PPO
batch_size:
    value: 512
clip_range:
    value: <function constant_fn.<locals>.func at 0x7f9cd4ed1d40>
clip_range_vf:
    value: None
curriculum_type:
    value: AutoCaLC_DualFramework
device:
    value: cuda
divergence_threshold:
    value: 0.1
early_termination_threshold:
    value: 0.7
ent_coef:
    value: 0.02
env:
    value: <stable_baselines3.common.vec_env.vec_monitor.VecMonitor object at 0x7f9cee3faad0>
ep_info_buffer:
    value: deque([], maxlen=100)
ep_success_buffer:
    value: deque([], maxlen=100)
eval_env:
    value: None
gae_lambda:
    value: 0.97
gamma:
    value: 0.995
learning_rate:
    value: 0.00025
lr_schedule:
    value: <function constant_fn.<locals>.func at 0x7f9cee2a6440>
max_episode_length:
    value: 250
max_grad_norm:
    value: 0.5
max_test_episodes:
    value: 5
max_training_steps:
    value: 200000
min_training_steps:
    value: 50000
mini_episode_length:
    value: 50
n_envs:
    value: 16
n_epochs:
    value: 15
n_steps:
    value: 256
num_timesteps:
    value: 0
observation_space:
    value: Box(56,)
patience:
    value: 3
policy:
    value: |-
        ActorCriticPolicy(
          (features_extractor): FlattenExtractor(
            (flatten): Flatten(start_dim=1, end_dim=-1)
          )
          (mlp_extractor): MlpExtractor(
            (shared_net): Sequential(
              (0): Linear(in_features=56, out_features=512, bias=True)
              (1): LeakyReLU(negative_slope=0.01)
              (2): Linear(in_features=512, out_features=256, bias=True)
              (3): LeakyReLU(negative_slope=0.01)
            )
            (policy_net): Sequential()
            (value_net): Sequential()
          )
          (action_net): Linear(in_features=256, out_features=9, bias=True)
          (value_net): Linear(in_features=256, out_features=1, bias=True)
        )
policy_class:
    value: <class 'stable_baselines3.common.policies.ActorCriticPolicy'>
policy_kwargs:
    value: '{''activation_fn'': <class ''torch.nn.modules.activation.LeakyReLU''>, ''net_arch'': [512, 256]}'
reference_states_size:
    value: 1000
rollout_buffer:
    value: <stable_baselines3.common.buffers.RolloutBuffer object at 0x7f9cdea19a50>
sde_sample_freq:
    value: -1
seed:
    value: 0
skip_frame:
    value: 3
start_time:
    value: 1.751922137437602e+09
target_kl:
    value: None
task_name:
    value: pushing
tensorboard_log:
    value: autocalcdual_pushing
testing_frequency_multiplier:
    value: 0.1
total_timesteps:
    value: 3000000
use_sde:
    value: "False"
verbose:
    value: 1
vf_coef:
    value: 0.5
